apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: postgres-secret
    namespace: default
    files:
      - values.yaml=encrypted-secret.yaml
resources:
  - git-repo.yaml
  - gitops.yaml